<?php

function tgasu_extra_block_info(){
  $blocks = array();

  $blocks['slider'] = array(
    'info' => t('Tgasu slider'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

function tgasu_extra_block_view($delta = ''){
 $block = array();
 $block['subject'] = t('<none>');
 $block['content'] = theme('tgasu_extra_slider');
 
 return $block;
}

function tgasu_extra_theme($existing, $type, $theme, $path){
  $themes = array();
  
  $themes = array(
  'tgasu_extra_slider' => array(
   'template' => 'tgasu-extra-slider',
   ),
  );
 
 return $themes;
}

function template_preprocess_tgasu_extra_slider(&$vars){
  $slides = array();
  $active = 'slide-2';
  $max_width = '940px';
  $min_height = '312px';
  
  $banner_dir = 'http://localhost/devel/' . drupal_get_path('theme', 'tgasu') . '/banner';
  
  $slides['main'] = array(
	'title' => 'First slide',
	'class' => '',
	'content' => "<img src='$banner_dir/1.jpg'>",
	'description' => '<p>Ну а тут можно выводить любой текст, в том числе и такие ссылки <a href="/node/1"><button class="btn btn-danger">подробнее</button></a></p>',
  );

  $slides['slide-2'] = array(
	'title' => 'Second slide',
	'class' => '',
	'content' => "<img src='$banner_dir/2.jpg'>",
	'description' => 'some text',
  );
  
  $vars['slides'] = $slides;
  $vars['active'] = $active;
  $vars['max_width'] = $max_width;
  $vars['min_height'] = $min_height;
}

function tgasu_extra_menu(){
  $items = array();
  
  $items['admin/config/media/tgasu-slider'] = array(
    'title' => t('Slider'),
    'description' => 'Bootstrap slider for <a href="http://tgasu.ru">tgasu.ru</a>',
    'page callback' => 'page_slides_callback',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

function page_slides_callback(){
  $page = array();
  /*
  $page['preview'] = array(
    '#title' => t('Preview'),
    '#type' => 'markup',
    '#markup' => theme('tgasu_extra_slider'),
  );
  */
  $page['title'] = array(
    '#title' => 'Title',
    '#type' => 'markup',
    '#markup' => 'Title',
  );
  
  return $page;
}
